"use client";

import { useState } from "react";
import { X, Download, ChevronLeft, ChevronRight, FileText, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Slide {
  title: string;
  content: string[];
}

interface SlidesModalProps {
  isOpen: boolean;
  onClose: () => void;
  concepts: string[];
  tasks: { id: string; title: string; duration: string }[];
  videoTitle?: string;
}

export function SlidesModal({ isOpen, onClose, concepts, tasks, videoTitle }: SlidesModalProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isExporting, setIsExporting] = useState(false);

  // Generate slides from concepts and tasks
  const slides: Slide[] = [
    {
      title: videoTitle || "Study Plan Overview",
      content: [
        `${concepts.length} Key Concepts`,
        `${tasks.length} Action Items`,
        "Generated by ChronoTask",
      ],
    },
    {
      title: "Key Concepts",
      content: concepts,
    },
    ...tasks.map((task, index) => ({
      title: `Task ${index + 1}`,
      content: [task.title, `Estimated time: ${task.duration}`],
    })),
    {
      title: "Summary",
      content: [
        "Review all key concepts",
        "Complete all tasks in order",
        "Track your progress",
        "Good luck with your learning!",
      ],
    },
  ];

  const nextSlide = () => {
    setCurrentSlide((prev) => Math.min(prev + 1, slides.length - 1));
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => Math.max(prev - 1, 0));
  };

  const exportToPDF = async () => {
    setIsExporting(true);
    
    try {
      // Create a printable HTML document
      const printContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${videoTitle || "Study Plan"} - Slides</title>
          <style>
            @page { size: landscape; margin: 0; }
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body { font-family: system-ui, -apple-system, sans-serif; }
            .slide {
              width: 100vw;
              height: 100vh;
              padding: 60px;
              display: flex;
              flex-direction: column;
              justify-content: center;
              background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
              page-break-after: always;
            }
            .slide:last-child { page-break-after: avoid; }
            .slide-number {
              position: absolute;
              bottom: 30px;
              right: 40px;
              font-size: 14px;
              color: #64748b;
            }
            h1 {
              font-size: 48px;
              color: #0f172a;
              margin-bottom: 40px;
              font-weight: 700;
            }
            ul {
              list-style: none;
              padding: 0;
            }
            li {
              font-size: 28px;
              color: #334155;
              margin-bottom: 20px;
              padding-left: 40px;
              position: relative;
            }
            li::before {
              content: "•";
              color: #2563eb;
              font-size: 32px;
              position: absolute;
              left: 0;
              top: -4px;
            }
            .title-slide h1 {
              font-size: 64px;
              text-align: center;
            }
            .title-slide ul {
              text-align: center;
            }
            .title-slide li {
              padding-left: 0;
            }
            .title-slide li::before {
              display: none;
            }
            .branding {
              position: absolute;
              bottom: 30px;
              left: 40px;
              font-size: 14px;
              color: #64748b;
            }
          </style>
        </head>
        <body>
          ${slides.map((slide, index) => `
            <div class="slide ${index === 0 ? 'title-slide' : ''}">
              <h1>${slide.title}</h1>
              <ul>
                ${slide.content.map(item => `<li>${item}</li>`).join('')}
              </ul>
              <div class="slide-number">${index + 1} / ${slides.length}</div>
              <div class="branding">ChronoTask</div>
            </div>
          `).join('')}
        </body>
        </html>
      `;

      // Open print dialog
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(printContent);
        printWindow.document.close();
        printWindow.focus();
        
        // Wait for content to load then print
        setTimeout(() => {
          printWindow.print();
          printWindow.close();
        }, 500);
      }
    } catch (error) {
      console.error('Error exporting PDF:', error);
    } finally {
      setIsExporting(false);
    }
  };

  if (!isOpen) return null;

  const slide = slides[currentSlide];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/70 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-4xl overflow-hidden animate-float-in">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-200 bg-slate-50">
          <div className="flex items-center gap-3">
            <FileText className="w-5 h-5 text-[#2563EB]" />
            <span className="font-medium text-slate-900">Slides Preview</span>
            <span className="text-sm text-slate-500">
              {currentSlide + 1} / {slides.length}
            </span>
          </div>
          <div className="flex items-center gap-2">
            <Button
              onClick={exportToPDF}
              disabled={isExporting}
              className="bg-[#2563EB] hover:bg-[#1d4ed8] text-white"
            >
              {isExporting ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Download className="w-4 h-4 mr-2" />
              )}
              Export PDF
            </Button>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center hover:bg-slate-200 transition-colors"
            >
              <X className="w-4 h-4 text-slate-500" />
            </button>
          </div>
        </div>

        {/* Slide Content */}
        <div className="aspect-video bg-gradient-to-br from-slate-50 to-slate-100 p-12 flex flex-col justify-center">
          <h2 className={`font-bold text-slate-900 mb-8 ${currentSlide === 0 ? 'text-4xl text-center' : 'text-3xl'}`}>
            {slide.title}
          </h2>
          <ul className={`space-y-4 ${currentSlide === 0 ? 'text-center' : ''}`}>
            {slide.content.map((item, index) => (
              <li 
                key={index}
                className={`text-xl text-slate-700 ${currentSlide === 0 ? '' : 'flex items-start gap-3'}`}
              >
                {currentSlide !== 0 && (
                  <span className="w-2 h-2 bg-[#2563EB] rounded-full mt-2.5 flex-shrink-0" />
                )}
                {item}
              </li>
            ))}
          </ul>
        </div>

        {/* Navigation */}
        <div className="flex items-center justify-between p-4 border-t border-slate-200 bg-slate-50">
          <Button
            variant="ghost"
            onClick={prevSlide}
            disabled={currentSlide === 0}
            className="text-slate-600"
          >
            <ChevronLeft className="w-4 h-4 mr-1" />
            Previous
          </Button>
          
          {/* Slide indicators */}
          <div className="flex items-center gap-1.5">
            {slides.map((_, index) => (
              <button
                key={index}
                onClick={() => setCurrentSlide(index)}
                className={`w-2 h-2 rounded-full transition-all ${
                  index === currentSlide 
                    ? 'bg-[#2563EB] w-6' 
                    : 'bg-slate-300 hover:bg-slate-400'
                }`}
              />
            ))}
          </div>
          
          <Button
            variant="ghost"
            onClick={nextSlide}
            disabled={currentSlide === slides.length - 1}
            className="text-slate-600"
          >
            Next
            <ChevronRight className="w-4 h-4 ml-1" />
          </Button>
        </div>
      </div>
    </div>
  );
}
